/**
 * VARIABLES
 */
const DISCRIMINANT_VALUE_INDEX = 1;

const TEST_EXPECTED_RESULT_INDEX = 1;
const TEST_CLASS_INDEX = 2;
const TEST_NAME_INDEX = 3;
const TEST_PARAMETERS_INDEX = 4;

const PARAMETER_VALUE_INDEX = 1;
const PARAMETER_NAME_INDEX = 2;

/**
 * REGEXES
 */
const INVOKER_DISCRIMINANTS_REGEX = 'i|inv|invoker';
const MODULE_DISCRIMINANTS_REGEX = 'm|mod|module';

const TEST_DISCRIMINANTS_REGEX = 't|test';
const TEST_ELEMENTS_REGEX = `(?:\\[(.*?)\\])\\((?:${TEST_DISCRIMINANTS_REGEX})\\:\\s?(?:(.*?)\\.)?(.*?)\\((.*)\\)\\)`;
const TEST_PARAMETER_NAME_REGEX = '[\\w\\d]+';

const PARAMETER_DISCRIMINANTS_REGEX = 'v|var|variable';
const PARAMETER_ELEMENTS_REGEX = `\\[(.*)?\\]\\((?:${PARAMETER_DISCRIMINANTS_REGEX})\\:\\s?([\\w\\d]+)\\)`;

const ELEMENT_DISCRIMINANTS_REGEX = `${INVOKER_DISCRIMINANTS_REGEX}|${MODULE_DISCRIMINANTS_REGEX}|${PARAMETER_DISCRIMINANTS_REGEX}|${TEST_DISCRIMINANTS_REGEX}`;
const ELEMENT_DETECTION_REGEX = `\\[.*?\\]\\((?:${ELEMENT_DISCRIMINANTS_REGEX})\\:\\s?.*?\\)+`;

const DISCRIMINANT_DETECTION_REGEX = `\\]\\((${ELEMENT_DISCRIMINANTS_REGEX})`;

module.exports = {
    DISCRIMINANT_VALUE_INDEX,
    TEST_EXPECTED_RESULT_INDEX,
    TEST_CLASS_INDEX,
    TEST_NAME_INDEX,
    TEST_PARAMETERS_INDEX,
    PARAMETER_VALUE_INDEX,
    PARAMETER_NAME_INDEX,

    TEST_ELEMENTS_REGEX,
    TEST_PARAMETER_NAME_REGEX,
    DISCRIMINANT_DETECTION_REGEX,
    PARAMETER_ELEMENTS_REGEX,
    ELEMENT_DETECTION_REGEX
};
